name: tasty-autocollect
version: 0.1.0.0
category: Testing
synopsis: Autocollection of tasty tests.
description: Autocollection of tasty tests. See README.md for more details.
license: BSD3
license-file: LICENSE.md
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md
  - CHANGELOG.md

github: brandonchinn178/tasty-autocollect

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

library:
  source-dirs: src
  dependencies:
    - base >= 4.14 && < 5
    - containers >= 0.6.4.1 && < 0.7
    - directory >= 1.3.6.0 && < 2
    - filepath >= 1.4.2.1 && < 2
    - ghc >= 8.10 && < 9.3
    - tasty >= 1.4.2.1 && < 2
    - template-haskell >= 2.16 && < 2.19
    - text >= 1.2.4.1 && < 3
    - transformers >= 0.5.6.2 && < 1

executable:
  source-dirs: exe
  main: Preprocessor.hs
  dependencies:
    - base >= 4.14 && < 5
    - tasty-autocollect
    - text >= 1.2.4.1 && < 3

tests:
  tasty-autocollect-tests:
    source-dirs: test
    main: Main.hs
    ghc-options: -F -pgmF=tasty-autocollect
    build-tools:
      - tasty-autocollect:tasty-autocollect
    dependencies:
      - base
      - bytestring
      - containers
      - tasty
      - tasty-autocollect
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck
