name: tasty-autocollect
version: 0.4.1
category: Testing
synopsis: Autocollection of tasty tests.
description: Autocollection of tasty tests. See README.md for more details.
license: BSD3
license-file: LICENSE.md
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md
  - CHANGELOG.md
  - test/**/*.golden

github: brandonchinn178/tasty-autocollect

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  other-modules:
    - Test.Tasty.AutoCollect.GHC
    - Test.Tasty.AutoCollect.GHC.Shim
    - Test.Tasty.AutoCollect.GHC.Shim_Common
  when:
    - condition: impl(ghc >= 9.6) && impl(ghc < 9.8)
      other-modules:
        - Test.Tasty.AutoCollect.GHC.Shim_9_6
    - condition: impl(ghc >= 9.4) && impl(ghc < 9.6)
      other-modules:
        - Test.Tasty.AutoCollect.GHC.Shim_9_4
    - condition: impl(ghc >= 9.2) && impl(ghc < 9.4)
      other-modules:
        - Test.Tasty.AutoCollect.GHC.Shim_9_2
    - condition: impl(ghc >= 9.0) && impl(ghc < 9.2)
      other-modules:
        - Test.Tasty.AutoCollect.GHC.Shim_9_0
  dependencies:
    - base >= 4.14 && < 5
    - bytestring < 0.13
    - containers < 0.7
    - directory < 2
    - filepath < 2
    - ghc >= 9.0 && < 9.7
    - tasty < 2
    - tasty-expected-failure < 1
    - template-haskell >= 2.16 && < 2.21
    - text < 3
    - transformers < 1

executable:
  source-dirs: exe
  main: Preprocessor.hs
  dependencies:
    - base >= 4.14 && < 5
    - tasty-autocollect
    - text < 3

tests:
  tasty-autocollect-tests:
    source-dirs: test
    main: Main.hs
    ghc-options: -F -pgmF=tasty-autocollect
    verbatim:
      # https://github.com/sol/hpack/issues/516
      build-tool-depends:
        tasty-autocollect:tasty-autocollect
    dependencies:
      - base
      - bytestring
      - containers
      - directory
      - explainable-predicates >= 0.1.2.0
      - filepath
      - tasty >= 1.4.2
      - tasty-autocollect
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck >= 0.8.1
      - temporary
      - text
      - typed-process >= 0.2.8.0
