name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        stack_yaml:
          # TODO: uncomment these
          # - stack-ghc-8.10.yaml
          - stack-ghc-9.0.yaml
          # - stack-ghc-9.2.yaml
        include:
          - stack_yaml: stack.yaml
            latest: true

    name: build_and_test (${{ matrix.stack_yaml }})
    runs-on: ubuntu-latest
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-cache-${{ hashFiles(matrix.stack_yaml, 'package.yaml') }}
      # TODO: uncomment
      # - name: Build + test
      #   run: stack test --coverage

      - name: Check that Cabal file was generated
        run: git diff --exit-code '*.cabal'

      # upload coverage data
      - name: Generate coverage data
        run: stack install hpc-lcov && hpc-lcov
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
        if: ${{ matrix.latest }}

  lint:
    runs-on: ubuntu-latest
    env:
      FOURMOLU_VERSION: '0.7.0.1'
    steps:
      - uses: actions/checkout@v2

      - name: Install fourmolu
        run: |
          curl -sSL \
            "https://github.com/fourmolu/fourmolu/releases/download/v${FOURMOLU_VERSION}/fourmolu-${FOURMOLU_VERSION}-linux-x86_64" \
            -o /usr/local/bin/fourmolu
          chmod +x /usr/local/bin/fourmolu
      - name: Run fourmolu
        run: fourmolu -m check $(git ls-files '*.hs')

  check_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-check_sdist-${{ hashFiles('stack.yaml') }}
      - name: Create sdist bundle
        run: stack sdist --test-tarball --tar-dir .
      - uses: actions/upload-artifact@v3
        with:
          name: tasty-autocollect-sdist
          path: tasty-autocollect-*.tar.gz
